env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  allow_failures:
    - osx_image: xcode8
  fast_finish: true
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8
    - os: osx
      language: generic
      osx_image: xcode8
      script:
        - swift build
        - swift test
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - swift build
        - swift test
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
script:
  - pod lib lint --allow-warnings --quick
  - set -o pipefail
  - xcodebuild test -scheme Himotoki-Mac -configuration Release ENABLE_TESTABILITY=YES GCC_GENERATE_DEBUGGING_SYMBOLS=NO | xcpretty -c
  - xcodebuild test -scheme Himotoki-iOS -configuration Release ENABLE_TESTABILITY=YES GCC_GENERATE_DEBUGGING_SYMBOLS=NO -sdk iphonesimulator -destination "name=iPhone 6s" | xcpretty -c
  - xcodebuild test -scheme Himotoki-tvOS -configuration Release ENABLE_TESTABILITY=YES GCC_GENERATE_DEBUGGING_SYMBOLS=NO -sdk appletvsimulator -destination "name=Apple TV 1080p" | xcpretty -c
  - xcodebuild build -scheme Himotoki-watchOS -configuration Release GCC_GENERATE_DEBUGGING_SYMBOLS=NO -sdk watchsimulator -destination "name=Apple Watch - 38mm" | xcpretty -c
notifications:
  email: false
